name: Checador de Preços Oba

on:
  schedule:
    # Roda a cada 1 dia (no minuto 0)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite rodar manualmente clicando num botão para testar

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Rodar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
